import Head from "next/head";
import { useState } from "react";

const questions = [
  {
    title: 'React - это ... ?',
    variants: ['библиотека', 'фреймворк', 'приложение'],
    correct: 0,
  },
  {
    title: 'Компонент - это ... ',
    variants: ['приложение', 'часть приложения или страницы', 'то, что я не знаю что такое'],
    correct: 1,
  },
  {
    title: 'Что такое JSX?',
    variants: [
      'Это простой HTML',
      'Это функция',
      'Это тот же HTML, но с возможностью выполнять JS-код',
    ],
    correct: 2,
  },
];

function Result({correct}) {
  return (
    <div className="result">
      <img src="https://cdn-icons-png.flaticon.com/512/2278/2278992.png" />
      <h2>Вы отгадали {correct} ответа из {questions.length}</h2>
      <a href='/'>
      <button>Попробовать снова</button>
      </a>
    </div>
  );
}

function Game({question, onClickVariant, step}) {
const percentage = Math.round((step / questions.length) * 100)


  return (
    <>
      <div className="progress">
        <div style={{ width: `${percentage}%` }} className="progress__inner"></div>
      </div>
      <h1>{question.title}</h1>
      <ul>
        {
          question.variants.map((text, index) => <li onClick={() => onClickVariant(index)} key={index}>{text}</li>)
        }
      </ul>
    </>
  );
}

export default function Home() {
const [step, setStep] =  useState(0)
const [currect, setCurrect] = useState(0)
const question = questions[step]

const onClickVariant = (index) => {
  console.log(step, index);
  setStep(step + 1)
  

  if(index === question.correct){
    setCurrect(currect + 1)
  }
}


  return (
    <>
      <Head>
        <title>Quis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="img/icon.png" />
      </Head>
      <div>
        <main>
        <section>
      <div className="container">

      <div className="App">
      {
        step !== questions.length ? (
        <Game step={step} question={question} onClickVariant={onClickVariant}/>
        ):(
          <Result correct={currect}/>
        )
      }
    </div>
    
    </div>
    </section>

        </main>
      </div>
    </>
  );
}
